
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const Card2: typeof import("../app/components/Card2.vue")['default']
export const ComponentsExplorer: typeof import("../app/components/ComponentsExplorer.vue")['default']
export const FileExplorer: typeof import("../app/components/FileExplorer.vue")['default']
export const TopBar: typeof import("../app/components/TopBar.vue")['default']
export const WelcomeSection: typeof import("../app/components/WelcomeSection.vue")['default']
export const WhatsAppFab: typeof import("../app/components/WhatsAppFab.vue")['default']
export const WorkflowTimeline: typeof import("../app/components/WorkflowTimeline.vue")['default']
export const BackupManager: typeof import("../app/components/admin/BackupManager.vue")['default']
export const CollectionFiles: typeof import("../app/components/admin/CollectionFiles.vue")['default']
export const DashboardHome: typeof import("../app/components/admin/DashboardHome.vue")['default']
export const DynamicBlockEditor: typeof import("../app/components/admin/DynamicBlockEditor.vue")['default']
export const FileManager: typeof import("../app/components/admin/FileManager.vue")['default']
export const FileToolbar: typeof import("../app/components/admin/FileToolbar.vue")['default']
export const ImageExplorer: typeof import("../app/components/admin/ImageExplorer.vue")['default']
export const MarkdownEditor: typeof import("../app/components/admin/MarkdownEditor.vue")['default']
export const MetaEditor: typeof import("../app/components/admin/MetaEditor.vue")['default']
export const RawEditor: typeof import("../app/components/admin/RawEditor.vue")['default']
export const SchemaEditor: typeof import("../app/components/admin/SchemaEditor.vue")['default']
export const Sidebar: typeof import("../app/components/admin/Sidebar.vue")['default']
export const Topbar: typeof import("../app/components/admin/Topbar.vue")['default']
export const WordmarkBuilder: typeof import("../app/components/admin/WordmarkBuilder.vue")['default']
export const VisualSplitEditor: typeof import("../app/components/admin/editors/VisualSplitEditor.vue")['default']
export const BackupRestore: typeof import("../app/components/admin/modals/BackupRestore.vue")['default']
export const CreateCollection: typeof import("../app/components/admin/modals/CreateCollection.vue")['default']
export const CreateFile: typeof import("../app/components/admin/modals/CreateFile.vue")['default']
export const CreateFolder: typeof import("../app/components/admin/modals/CreateFolder.vue")['default']
export const Banner: typeof import("../app/components/content/Banner.vue")['default']
export const Callout: typeof import("../app/components/content/Callout.vue")['default']
export const CardHorizontal: typeof import("../app/components/content/CardHorizontal.vue")['default']
export const CardHorizontalVideo: typeof import("../app/components/content/CardHorizontalVideo.vue")['default']
export const Carrossel: typeof import("../app/components/content/Carrossel.vue")['default']
export const Feature: typeof import("../app/components/content/Feature.vue")['default']
export const Features: typeof import("../app/components/content/Features.vue")['default']
export const ListFolders: typeof import("../app/components/content/ListFolders.vue")['default']
export const Blog: typeof import("../app/components/content/Listfiles/Blog.vue")['default']
export const Carrosel: typeof import("../app/components/content/Listfiles/Carrosel.vue")['default']
export const Grid: typeof import("../app/components/content/Listfiles/Grid.vue")['default']
export const List: typeof import("../app/components/content/Listfiles/List.vue")['default']
export const Raw: typeof import("../app/components/content/Listfiles/Raw.vue")['default']
export const Supergrid: typeof import("../app/components/content/Listfiles/Supergrid.vue")['default']
export const Listfiles: typeof import("../app/components/content/Listfiles/index.vue")['default']
export const Section: typeof import("../app/components/content/Section.vue")['default']
export const Wrapper: typeof import("../app/components/content/Wrapper.vue")['default']
export const ProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProsePre: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue")['default']
export const ProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const MDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCCached: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
export const MDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const AutoComplete: typeof import("primevue/autocomplete")['default']
export const Calendar: typeof import("primevue/calendar")['default']
export const CascadeSelect: typeof import("primevue/cascadeselect")['default']
export const Checkbox: typeof import("primevue/checkbox")['default']
export const CheckboxGroup: typeof import("primevue/checkboxgroup")['default']
export const Chips: typeof import("primevue/chips")['default']
export const ColorPicker: typeof import("primevue/colorpicker")['default']
export const DatePicker: typeof import("primevue/datepicker")['default']
export const Dropdown: typeof import("primevue/dropdown")['default']
export const FloatLabel: typeof import("primevue/floatlabel")['default']
export const Fluid: typeof import("primevue/fluid")['default']
export const IconField: typeof import("primevue/iconfield")['default']
export const IftaLabel: typeof import("primevue/iftalabel")['default']
export const InputChips: typeof import("primevue/inputchips")['default']
export const InputGroup: typeof import("primevue/inputgroup")['default']
export const InputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const InputIcon: typeof import("primevue/inputicon")['default']
export const InputMask: typeof import("primevue/inputmask")['default']
export const InputNumber: typeof import("primevue/inputnumber")['default']
export const InputOtp: typeof import("primevue/inputotp")['default']
export const InputSwitch: typeof import("primevue/inputswitch")['default']
export const InputText: typeof import("primevue/inputtext")['default']
export const Knob: typeof import("primevue/knob")['default']
export const Listbox: typeof import("primevue/listbox")['default']
export const MultiSelect: typeof import("primevue/multiselect")['default']
export const Password: typeof import("primevue/password")['default']
export const RadioButton: typeof import("primevue/radiobutton")['default']
export const RadioButtonGroup: typeof import("primevue/radiobuttongroup")['default']
export const Rating: typeof import("primevue/rating")['default']
export const Select: typeof import("primevue/select")['default']
export const SelectButton: typeof import("primevue/selectbutton")['default']
export const Slider: typeof import("primevue/slider")['default']
export const Textarea: typeof import("primevue/textarea")['default']
export const ToggleButton: typeof import("primevue/togglebutton")['default']
export const ToggleSwitch: typeof import("primevue/toggleswitch")['default']
export const TreeSelect: typeof import("primevue/treeselect")['default']
export const Button: typeof import("primevue/button")['default']
export const ButtonGroup: typeof import("primevue/buttongroup")['default']
export const SpeedDial: typeof import("primevue/speeddial")['default']
export const SplitButton: typeof import("primevue/splitbutton")['default']
export const Column: typeof import("primevue/column")['default']
export const Row: typeof import("primevue/row")['default']
export const ColumnGroup: typeof import("primevue/columngroup")['default']
export const DataTable: typeof import("primevue/datatable")['default']
export const DataView: typeof import("primevue/dataview")['default']
export const OrderList: typeof import("primevue/orderlist")['default']
export const OrganizationChart: typeof import("primevue/organizationchart")['default']
export const Paginator: typeof import("primevue/paginator")['default']
export const PickList: typeof import("primevue/picklist")['default']
export const Tree: typeof import("primevue/tree")['default']
export const TreeTable: typeof import("primevue/treetable")['default']
export const Timeline: typeof import("primevue/timeline")['default']
export const VirtualScroller: typeof import("primevue/virtualscroller")['default']
export const Accordion: typeof import("primevue/accordion")['default']
export const AccordionPanel: typeof import("primevue/accordionpanel")['default']
export const AccordionHeader: typeof import("primevue/accordionheader")['default']
export const AccordionContent: typeof import("primevue/accordioncontent")['default']
export const AccordionTab: typeof import("primevue/accordiontab")['default']
export const Card: typeof import("primevue/card")['default']
export const DeferredContent: typeof import("primevue/deferredcontent")['default']
export const Divider: typeof import("primevue/divider")['default']
export const Fieldset: typeof import("primevue/fieldset")['default']
export const Panel: typeof import("primevue/panel")['default']
export const ScrollPanel: typeof import("primevue/scrollpanel")['default']
export const Splitter: typeof import("primevue/splitter")['default']
export const SplitterPanel: typeof import("primevue/splitterpanel")['default']
export const Stepper: typeof import("primevue/stepper")['default']
export const StepList: typeof import("primevue/steplist")['default']
export const Step: typeof import("primevue/step")['default']
export const StepItem: typeof import("primevue/stepitem")['default']
export const StepPanels: typeof import("primevue/steppanels")['default']
export const StepPanel: typeof import("primevue/steppanel")['default']
export const TabView: typeof import("primevue/tabview")['default']
export const Tabs: typeof import("primevue/tabs")['default']
export const TabList: typeof import("primevue/tablist")['default']
export const Tab: typeof import("primevue/tab")['default']
export const TabPanels: typeof import("primevue/tabpanels")['default']
export const TabPanel: typeof import("primevue/tabpanel")['default']
export const Toolbar: typeof import("primevue/toolbar")['default']
export const ConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const ConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const Dialog: typeof import("primevue/dialog")['default']
export const Drawer: typeof import("primevue/drawer")['default']
export const DynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const OverlayPanel: typeof import("primevue/overlaypanel")['default']
export const Popover: typeof import("primevue/popover")['default']
export const FileUpload: typeof import("primevue/fileupload")['default']
export const Breadcrumb: typeof import("primevue/breadcrumb")['default']
export const ContextMenu: typeof import("primevue/contextmenu")['default']
export const Dock: typeof import("primevue/dock")['default']
export const Menu: typeof import("primevue/menu")['default']
export const Menubar: typeof import("primevue/menubar")['default']
export const MegaMenu: typeof import("primevue/megamenu")['default']
export const PanelMenu: typeof import("primevue/panelmenu")['default']
export const Steps: typeof import("primevue/steps")['default']
export const TabMenu: typeof import("primevue/tabmenu")['default']
export const TieredMenu: typeof import("primevue/tieredmenu")['default']
export const Message: typeof import("primevue/message")['default']
export const InlineMessage: typeof import("primevue/inlinemessage")['default']
export const Toast: typeof import("primevue/toast")['default']
export const Carousel: typeof import("primevue/carousel")['default']
export const Galleria: typeof import("primevue/galleria")['default']
export const Image: typeof import("primevue/image")['default']
export const ImageCompare: typeof import("primevue/imagecompare")['default']
export const Avatar: typeof import("primevue/avatar")['default']
export const AvatarGroup: typeof import("primevue/avatargroup")['default']
export const Badge: typeof import("primevue/badge")['default']
export const BlockUI: typeof import("primevue/blockui")['default']
export const Chip: typeof import("primevue/chip")['default']
export const Inplace: typeof import("primevue/inplace")['default']
export const MeterGroup: typeof import("primevue/metergroup")['default']
export const OverlayBadge: typeof import("primevue/overlaybadge")['default']
export const ScrollTop: typeof import("primevue/scrolltop")['default']
export const Skeleton: typeof import("primevue/skeleton")['default']
export const ProgressBar: typeof import("primevue/progressbar")['default']
export const ProgressSpinner: typeof import("primevue/progressspinner")['default']
export const Tag: typeof import("primevue/tag")['default']
export const Terminal: typeof import("primevue/terminal")['default']
export const Form: typeof import("@primevue/forms/form")['default']
export const FormField: typeof import("@primevue/forms/formfield")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyCard2: LazyComponent<typeof import("../app/components/Card2.vue")['default']>
export const LazyComponentsExplorer: LazyComponent<typeof import("../app/components/ComponentsExplorer.vue")['default']>
export const LazyFileExplorer: LazyComponent<typeof import("../app/components/FileExplorer.vue")['default']>
export const LazyTopBar: LazyComponent<typeof import("../app/components/TopBar.vue")['default']>
export const LazyWelcomeSection: LazyComponent<typeof import("../app/components/WelcomeSection.vue")['default']>
export const LazyWhatsAppFab: LazyComponent<typeof import("../app/components/WhatsAppFab.vue")['default']>
export const LazyWorkflowTimeline: LazyComponent<typeof import("../app/components/WorkflowTimeline.vue")['default']>
export const LazyBackupManager: LazyComponent<typeof import("../app/components/admin/BackupManager.vue")['default']>
export const LazyCollectionFiles: LazyComponent<typeof import("../app/components/admin/CollectionFiles.vue")['default']>
export const LazyDashboardHome: LazyComponent<typeof import("../app/components/admin/DashboardHome.vue")['default']>
export const LazyDynamicBlockEditor: LazyComponent<typeof import("../app/components/admin/DynamicBlockEditor.vue")['default']>
export const LazyFileManager: LazyComponent<typeof import("../app/components/admin/FileManager.vue")['default']>
export const LazyFileToolbar: LazyComponent<typeof import("../app/components/admin/FileToolbar.vue")['default']>
export const LazyImageExplorer: LazyComponent<typeof import("../app/components/admin/ImageExplorer.vue")['default']>
export const LazyMarkdownEditor: LazyComponent<typeof import("../app/components/admin/MarkdownEditor.vue")['default']>
export const LazyMetaEditor: LazyComponent<typeof import("../app/components/admin/MetaEditor.vue")['default']>
export const LazyRawEditor: LazyComponent<typeof import("../app/components/admin/RawEditor.vue")['default']>
export const LazySchemaEditor: LazyComponent<typeof import("../app/components/admin/SchemaEditor.vue")['default']>
export const LazySidebar: LazyComponent<typeof import("../app/components/admin/Sidebar.vue")['default']>
export const LazyTopbar: LazyComponent<typeof import("../app/components/admin/Topbar.vue")['default']>
export const LazyWordmarkBuilder: LazyComponent<typeof import("../app/components/admin/WordmarkBuilder.vue")['default']>
export const LazyVisualSplitEditor: LazyComponent<typeof import("../app/components/admin/editors/VisualSplitEditor.vue")['default']>
export const LazyBackupRestore: LazyComponent<typeof import("../app/components/admin/modals/BackupRestore.vue")['default']>
export const LazyCreateCollection: LazyComponent<typeof import("../app/components/admin/modals/CreateCollection.vue")['default']>
export const LazyCreateFile: LazyComponent<typeof import("../app/components/admin/modals/CreateFile.vue")['default']>
export const LazyCreateFolder: LazyComponent<typeof import("../app/components/admin/modals/CreateFolder.vue")['default']>
export const LazyBanner: LazyComponent<typeof import("../app/components/content/Banner.vue")['default']>
export const LazyCallout: LazyComponent<typeof import("../app/components/content/Callout.vue")['default']>
export const LazyCardHorizontal: LazyComponent<typeof import("../app/components/content/CardHorizontal.vue")['default']>
export const LazyCardHorizontalVideo: LazyComponent<typeof import("../app/components/content/CardHorizontalVideo.vue")['default']>
export const LazyCarrossel: LazyComponent<typeof import("../app/components/content/Carrossel.vue")['default']>
export const LazyFeature: LazyComponent<typeof import("../app/components/content/Feature.vue")['default']>
export const LazyFeatures: LazyComponent<typeof import("../app/components/content/Features.vue")['default']>
export const LazyListFolders: LazyComponent<typeof import("../app/components/content/ListFolders.vue")['default']>
export const LazyBlog: LazyComponent<typeof import("../app/components/content/Listfiles/Blog.vue")['default']>
export const LazyCarrosel: LazyComponent<typeof import("../app/components/content/Listfiles/Carrosel.vue")['default']>
export const LazyGrid: LazyComponent<typeof import("../app/components/content/Listfiles/Grid.vue")['default']>
export const LazyList: LazyComponent<typeof import("../app/components/content/Listfiles/List.vue")['default']>
export const LazyRaw: LazyComponent<typeof import("../app/components/content/Listfiles/Raw.vue")['default']>
export const LazySupergrid: LazyComponent<typeof import("../app/components/content/Listfiles/Supergrid.vue")['default']>
export const LazyListfiles: LazyComponent<typeof import("../app/components/content/Listfiles/index.vue")['default']>
export const LazySection: LazyComponent<typeof import("../app/components/content/Section.vue")['default']>
export const LazyWrapper: LazyComponent<typeof import("../app/components/content/Wrapper.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
export const LazyProsePre: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue")['default']>
export const LazyProseScript: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
export const LazyMDC: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
export const LazyMDCCached: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
export const LazyMDCRenderer: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
export const LazyMDCSlot: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
export const LazyAutoComplete: LazyComponent<typeof import("primevue/autocomplete")['default']>
export const LazyCalendar: LazyComponent<typeof import("primevue/calendar")['default']>
export const LazyCascadeSelect: LazyComponent<typeof import("primevue/cascadeselect")['default']>
export const LazyCheckbox: LazyComponent<typeof import("primevue/checkbox")['default']>
export const LazyCheckboxGroup: LazyComponent<typeof import("primevue/checkboxgroup")['default']>
export const LazyChips: LazyComponent<typeof import("primevue/chips")['default']>
export const LazyColorPicker: LazyComponent<typeof import("primevue/colorpicker")['default']>
export const LazyDatePicker: LazyComponent<typeof import("primevue/datepicker")['default']>
export const LazyDropdown: LazyComponent<typeof import("primevue/dropdown")['default']>
export const LazyFloatLabel: LazyComponent<typeof import("primevue/floatlabel")['default']>
export const LazyFluid: LazyComponent<typeof import("primevue/fluid")['default']>
export const LazyIconField: LazyComponent<typeof import("primevue/iconfield")['default']>
export const LazyIftaLabel: LazyComponent<typeof import("primevue/iftalabel")['default']>
export const LazyInputChips: LazyComponent<typeof import("primevue/inputchips")['default']>
export const LazyInputGroup: LazyComponent<typeof import("primevue/inputgroup")['default']>
export const LazyInputGroupAddon: LazyComponent<typeof import("primevue/inputgroupaddon")['default']>
export const LazyInputIcon: LazyComponent<typeof import("primevue/inputicon")['default']>
export const LazyInputMask: LazyComponent<typeof import("primevue/inputmask")['default']>
export const LazyInputNumber: LazyComponent<typeof import("primevue/inputnumber")['default']>
export const LazyInputOtp: LazyComponent<typeof import("primevue/inputotp")['default']>
export const LazyInputSwitch: LazyComponent<typeof import("primevue/inputswitch")['default']>
export const LazyInputText: LazyComponent<typeof import("primevue/inputtext")['default']>
export const LazyKnob: LazyComponent<typeof import("primevue/knob")['default']>
export const LazyListbox: LazyComponent<typeof import("primevue/listbox")['default']>
export const LazyMultiSelect: LazyComponent<typeof import("primevue/multiselect")['default']>
export const LazyPassword: LazyComponent<typeof import("primevue/password")['default']>
export const LazyRadioButton: LazyComponent<typeof import("primevue/radiobutton")['default']>
export const LazyRadioButtonGroup: LazyComponent<typeof import("primevue/radiobuttongroup")['default']>
export const LazyRating: LazyComponent<typeof import("primevue/rating")['default']>
export const LazySelect: LazyComponent<typeof import("primevue/select")['default']>
export const LazySelectButton: LazyComponent<typeof import("primevue/selectbutton")['default']>
export const LazySlider: LazyComponent<typeof import("primevue/slider")['default']>
export const LazyTextarea: LazyComponent<typeof import("primevue/textarea")['default']>
export const LazyToggleButton: LazyComponent<typeof import("primevue/togglebutton")['default']>
export const LazyToggleSwitch: LazyComponent<typeof import("primevue/toggleswitch")['default']>
export const LazyTreeSelect: LazyComponent<typeof import("primevue/treeselect")['default']>
export const LazyButton: LazyComponent<typeof import("primevue/button")['default']>
export const LazyButtonGroup: LazyComponent<typeof import("primevue/buttongroup")['default']>
export const LazySpeedDial: LazyComponent<typeof import("primevue/speeddial")['default']>
export const LazySplitButton: LazyComponent<typeof import("primevue/splitbutton")['default']>
export const LazyColumn: LazyComponent<typeof import("primevue/column")['default']>
export const LazyRow: LazyComponent<typeof import("primevue/row")['default']>
export const LazyColumnGroup: LazyComponent<typeof import("primevue/columngroup")['default']>
export const LazyDataTable: LazyComponent<typeof import("primevue/datatable")['default']>
export const LazyDataView: LazyComponent<typeof import("primevue/dataview")['default']>
export const LazyOrderList: LazyComponent<typeof import("primevue/orderlist")['default']>
export const LazyOrganizationChart: LazyComponent<typeof import("primevue/organizationchart")['default']>
export const LazyPaginator: LazyComponent<typeof import("primevue/paginator")['default']>
export const LazyPickList: LazyComponent<typeof import("primevue/picklist")['default']>
export const LazyTree: LazyComponent<typeof import("primevue/tree")['default']>
export const LazyTreeTable: LazyComponent<typeof import("primevue/treetable")['default']>
export const LazyTimeline: LazyComponent<typeof import("primevue/timeline")['default']>
export const LazyVirtualScroller: LazyComponent<typeof import("primevue/virtualscroller")['default']>
export const LazyAccordion: LazyComponent<typeof import("primevue/accordion")['default']>
export const LazyAccordionPanel: LazyComponent<typeof import("primevue/accordionpanel")['default']>
export const LazyAccordionHeader: LazyComponent<typeof import("primevue/accordionheader")['default']>
export const LazyAccordionContent: LazyComponent<typeof import("primevue/accordioncontent")['default']>
export const LazyAccordionTab: LazyComponent<typeof import("primevue/accordiontab")['default']>
export const LazyCard: LazyComponent<typeof import("primevue/card")['default']>
export const LazyDeferredContent: LazyComponent<typeof import("primevue/deferredcontent")['default']>
export const LazyDivider: LazyComponent<typeof import("primevue/divider")['default']>
export const LazyFieldset: LazyComponent<typeof import("primevue/fieldset")['default']>
export const LazyPanel: LazyComponent<typeof import("primevue/panel")['default']>
export const LazyScrollPanel: LazyComponent<typeof import("primevue/scrollpanel")['default']>
export const LazySplitter: LazyComponent<typeof import("primevue/splitter")['default']>
export const LazySplitterPanel: LazyComponent<typeof import("primevue/splitterpanel")['default']>
export const LazyStepper: LazyComponent<typeof import("primevue/stepper")['default']>
export const LazyStepList: LazyComponent<typeof import("primevue/steplist")['default']>
export const LazyStep: LazyComponent<typeof import("primevue/step")['default']>
export const LazyStepItem: LazyComponent<typeof import("primevue/stepitem")['default']>
export const LazyStepPanels: LazyComponent<typeof import("primevue/steppanels")['default']>
export const LazyStepPanel: LazyComponent<typeof import("primevue/steppanel")['default']>
export const LazyTabView: LazyComponent<typeof import("primevue/tabview")['default']>
export const LazyTabs: LazyComponent<typeof import("primevue/tabs")['default']>
export const LazyTabList: LazyComponent<typeof import("primevue/tablist")['default']>
export const LazyTab: LazyComponent<typeof import("primevue/tab")['default']>
export const LazyTabPanels: LazyComponent<typeof import("primevue/tabpanels")['default']>
export const LazyTabPanel: LazyComponent<typeof import("primevue/tabpanel")['default']>
export const LazyToolbar: LazyComponent<typeof import("primevue/toolbar")['default']>
export const LazyConfirmDialog: LazyComponent<typeof import("primevue/confirmdialog")['default']>
export const LazyConfirmPopup: LazyComponent<typeof import("primevue/confirmpopup")['default']>
export const LazyDialog: LazyComponent<typeof import("primevue/dialog")['default']>
export const LazyDrawer: LazyComponent<typeof import("primevue/drawer")['default']>
export const LazyDynamicDialog: LazyComponent<typeof import("primevue/dynamicdialog")['default']>
export const LazyOverlayPanel: LazyComponent<typeof import("primevue/overlaypanel")['default']>
export const LazyPopover: LazyComponent<typeof import("primevue/popover")['default']>
export const LazyFileUpload: LazyComponent<typeof import("primevue/fileupload")['default']>
export const LazyBreadcrumb: LazyComponent<typeof import("primevue/breadcrumb")['default']>
export const LazyContextMenu: LazyComponent<typeof import("primevue/contextmenu")['default']>
export const LazyDock: LazyComponent<typeof import("primevue/dock")['default']>
export const LazyMenu: LazyComponent<typeof import("primevue/menu")['default']>
export const LazyMenubar: LazyComponent<typeof import("primevue/menubar")['default']>
export const LazyMegaMenu: LazyComponent<typeof import("primevue/megamenu")['default']>
export const LazyPanelMenu: LazyComponent<typeof import("primevue/panelmenu")['default']>
export const LazySteps: LazyComponent<typeof import("primevue/steps")['default']>
export const LazyTabMenu: LazyComponent<typeof import("primevue/tabmenu")['default']>
export const LazyTieredMenu: LazyComponent<typeof import("primevue/tieredmenu")['default']>
export const LazyMessage: LazyComponent<typeof import("primevue/message")['default']>
export const LazyInlineMessage: LazyComponent<typeof import("primevue/inlinemessage")['default']>
export const LazyToast: LazyComponent<typeof import("primevue/toast")['default']>
export const LazyCarousel: LazyComponent<typeof import("primevue/carousel")['default']>
export const LazyGalleria: LazyComponent<typeof import("primevue/galleria")['default']>
export const LazyImage: LazyComponent<typeof import("primevue/image")['default']>
export const LazyImageCompare: LazyComponent<typeof import("primevue/imagecompare")['default']>
export const LazyAvatar: LazyComponent<typeof import("primevue/avatar")['default']>
export const LazyAvatarGroup: LazyComponent<typeof import("primevue/avatargroup")['default']>
export const LazyBadge: LazyComponent<typeof import("primevue/badge")['default']>
export const LazyBlockUI: LazyComponent<typeof import("primevue/blockui")['default']>
export const LazyChip: LazyComponent<typeof import("primevue/chip")['default']>
export const LazyInplace: LazyComponent<typeof import("primevue/inplace")['default']>
export const LazyMeterGroup: LazyComponent<typeof import("primevue/metergroup")['default']>
export const LazyOverlayBadge: LazyComponent<typeof import("primevue/overlaybadge")['default']>
export const LazyScrollTop: LazyComponent<typeof import("primevue/scrolltop")['default']>
export const LazySkeleton: LazyComponent<typeof import("primevue/skeleton")['default']>
export const LazyProgressBar: LazyComponent<typeof import("primevue/progressbar")['default']>
export const LazyProgressSpinner: LazyComponent<typeof import("primevue/progressspinner")['default']>
export const LazyTag: LazyComponent<typeof import("primevue/tag")['default']>
export const LazyTerminal: LazyComponent<typeof import("primevue/terminal")['default']>
export const LazyForm: LazyComponent<typeof import("@primevue/forms/form")['default']>
export const LazyFormField: LazyComponent<typeof import("@primevue/forms/formfield")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
